apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - all.yaml
patches:
  - path: patch-interpolated.yaml
    target:
      kind: Deployment
      name: ".*helm-advanced-features"
